set_attributes:
  fields:
    device_id:
      example: "1234567890"
    attributes:
      example: 
        "power": "on"
        "mode": "cool"

set_mode:
send_command:
  fields:
    device_id:
      example: "1234567890"
    cmd_type:
      example: 2
    cmd_body:
      example: "B0FF01370E0000A500"
